### ISSUE TITLE
App: Tiny

### ISSUE THREAD

**Issue by leomp12** [ecomplus/app-tiny#10]
> Assim como o Bling

Precisamos de um release estável do Tiny (já temos ?), como estamos com os issues antigos?

- [x] https://github.com/ecomplus/app-tiny/issues/8
- [ ] https://github.com/ecomplus/app-tiny/issues/7

O que acho que é crucial e precisamos testar e validar em cenários diversos:

- [x] Configuração no admin finalizada e simples (como possível);
- [x] Envio de produtos da plataforma para o ERP com o máximo de dados que o Tiny aceitar;
- [x] Estoque sincronizando;
- [x] Pedidos enviados automaticamente da plataforma para o ERP;

@matheusgnreis pode nos ajudar a testar e reportar improves e fixes aqui por favor (se houverem)?

@talissonf me dá uma mão com este checklist por favor?

**Comment by talissonf** [comment]
Eu fiz um release hoje pra arrumar as inconsistências do app.
@matheusgnreis quando puder pode testar.

**Comment by vitorrgg** [comment]
Os pontos cruciais estão todos funcionando. 
Não consegui importar produto do tiny para a E-Com Plus, isso ainda é só com aquela lista de IDs @talissonf ?

**Comment by talissonf** [comment]
> Os pontos cruciais estão todos funcionando.

:woman_dancing: 

> Não consegui importar produto do tiny para a E-Com Plus, isso ainda é só com aquela lista de IDs @talissonf ?

@vitorrgg  https://github.com/ecomplus/app-tiny/wiki/Usage

**Comment by matheusgnreis** [comment]
@talissonf fui fazer um teste aqui e nenhum produto foi enviado, no log do tiny está escrito isso aqui:

ecomplus-modules [Mon Apr 13 2020 19:04:19 GMT-0300 (Brasilia Standard Time)] 
Save 171 products | #1035
  ---  //  ---  

ecomplus-modules [Mon Apr 13 2020 19:04:25 GMT-0300 (Brasilia Standard Time)] 
--> Sending 100 products to the bling | store #1035
  ---  //  ---  

ecomplus-modules [Mon Apr 13 2020 19:06:01 GMT-0300 (Brasilia Standard Time)] 
Save 9 products | #1035
  ---  //  ---  

Veja que ali está falando que está enviando pro Bling, está errado né? No caso, nessa conta eu tenho ativo Bling e Tiny. Na E-Com Club as vezes acontece isso, quando o lojista usa um ou outro, as vezes usa ambos para testar

**Comment by talissonf** [comment]
@matheusgnreis a sincronização tem um delay, ela inicia a cada 2 minutos, porém, a api do tiny atinge o limite de requisição muito rápido, até mesmo porque as vezes pode haver outros serviços que dependam da api do tiny no momento. Porem os produtos estão sendo sincronizados. 

Eu escrevi bling ao inves de tiny :$

Log da sincronização de produtos
```bash

ecomplus-modules [Mon Apr 13 2020 19:04:19 GMT-0300 (Brasilia Standard Time)] 
Save 171 products | #1035
  ---  //  ---  

ecomplus-modules [Mon Apr 13 2020 19:04:25 GMT-0300 (Brasilia Standard Time)] 
--> Sending 100 products to the bling | store #1035
  ---  //  ---  

ecomplus-modules [Mon Apr 13 2020 19:06:01 GMT-0300 (Brasilia Standard Time)] 
Save 9 products | #1035
  ---  //  ---  

ecomplus-modules [Mon Apr 13 2020 19:24:56 GMT-0300 (Brasilia Standard Time)] 
--> SYNC
{
    "sync": "products",
    "date": "2020-04-13T22:24:56.839Z",
    "storeId": 1035,
    "total": 100,
    "success": 0,
    "errosCount": 100
}
  ---  //  ---  

ecomplus-modules [Mon Apr 13 2020 19:27:59 GMT-0300 (Brasilia Standard Time)] 
--> Sending 80 products to the bling | store #1035
  ---  //  ---  

ecomplus-modules [Mon Apr 13 2020 19:44:53 GMT-0300 (Brasilia Standard Time)] 
--> SYNC
{
    "sync": "products",
    "date": "2020-04-13T22:44:53.178Z",
    "storeId": 1035,
    "total": 80,
    "success": 0,
    "errosCount": 80
}
  ---  //  ---  
```

Segundo o log houve erro na sincronização, no hidden_data do app tem sempre o log da ultima sincronização com o detalhe dos erros. No log eu só tenho salvo erros da aplicação.

**Comment by matheusgnreis** [comment]
@talissonf Problema que não tem nenhum produto no tiny, essa conta é antiga. É aquela que usamos pra implemntar o tiny, que o time do tiny liberou pra sempre o acesso. Apenas renovei o token, mas se quiser posso criar uma nova conta para testar.

**Comment by matheusgnreis** [comment]
Não consegui criar outra conta no Tiny, por não ter recebido emails de acesso do Tiny, então não consigo testar além dessa conta

**Comment by leomp12** [comment]
Pessoal, precisamos definir isto aqui, que pé que ficou?

**Comment by talissonf** [comment]
Ta rodando suave 🌴
